version: "2"
services:
    influxdb:
        build: ~/workspace/docker/influxdb/
        ports:
            - "8086:8086"
            - "8083:8083"
            - "8088:8088"
    grafana:
        build: ~/workspace/docker/grafana/
        ports:
            - "3000:3000"
        links: 
            - "influxdb:influxdb"
        depends_on:
            - influxdb

